{% set name = "mapd-core-cpu" %}
{% set version = "4.6.1" %}
{% set sha256 = "f1abd5db7d494283300377e69ad5dbd3c2b5bb7447209651eb343cfdf94ca317" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mapd/mapd-core/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}   # required for C++ headers
    - cmake
    - make
    - maven
    - openjdk 8.*
    - wget
    - clangdev 7.*
    - go
    - bisonpp
  host:
    - snappy  # required for mapd-core > 4.5.0
    - arrow-cpp 0.12.*
    - blosc
    - boost-cpp >=1.68
    - double-conversion
    - libgdal
    - flex
    - gflags
    - glog
    - libarchive
    - libkml
    - libpng
    - llvmdev 7.*
    - openssl
    - parquet-cpp
    - thrift-cpp >=0.11.0
    - ncurses
  run:
    - boost-cpp >=1.68
    - libgdal
    - glog
    - gflags
    - openjdk 8.*
    - ncurses
    - xz
    - bzip2
    - zlib
about:
  home: https://www.mapd.com/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: 'The MapD Core database'

  description: |
    MapD Core is an in-memory, column store, SQL relational database 
    that was designed from the ground up to run on GPUs.
  doc_url: https://www.mapd.com/docs/
  dev_url: https://github.com/mapd/mapd-core

extra:
  recipe-maintainers:
    - xmnlab
    - pearu
    - andrewseidl
